// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6qB74FLjN67gn8rEwUVRi18S8_u_mdGQ',
    appId: '1:836888341029:web:d66256df975f34ac996dcc',
    messagingSenderId: '836888341029',
    projectId: 'smart-food-delivery-c3172',
    authDomain: 'smart-food-delivery-c3172.firebaseapp.com',
    storageBucket: 'smart-food-delivery-c3172.firebasestorage.app',
    measurementId: 'G-XLELB7JZG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Hd8ikSkoCeE4KrSsbYg-UM1gLN_QTRk',
    appId: '1:836888341029:android:90de997fc386fb53996dcc',
    messagingSenderId: '836888341029',
    projectId: 'smart-food-delivery-c3172',
    storageBucket: 'smart-food-delivery-c3172.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ELhnUfmVDzUOKONo8K2VZrpzgUH1gTw',
    appId: '1:836888341029:ios:fcd1e9c4996933a4996dcc',
    messagingSenderId: '836888341029',
    projectId: 'smart-food-delivery-c3172',
    storageBucket: 'smart-food-delivery-c3172.firebasestorage.app',
    iosClientId: '836888341029-nlvnhicduq5j4jahdv1aqo7qjogr470i.apps.googleusercontent.com',
    iosBundleId: 'com.example.sfdaMark1',
  );
}
